- name: Install php-redis
  apt:
    name: php-redis
  notify: restart php-fpm

- name: Catch worker output on php-fpm
  lineinfile:
    dest: "{{ php_fpm_pool_conf_path }}"
    regexp: "^;*catch_workers_output = yes$"
    line: "catch_workers_output = yes"
  notify: restart php-fpm

- name: CLI PHP should have no memory limit
  copy:
    src: files/99-cli.ini
    dest: "/etc/php/{{ php_version }}/cli/conf.d"
    mode: 0644
  tags: php-cli

- name: Ensure we're using the correct CLI version
  community.general.alternatives:
    name: php
    path: "/usr/bin/php{{ php_version }}"
